CREATE DATABASE ATIVIDADE_PESSOAS;

USE ATIVIDADE_PESSOAS;

CREATE TABLE PESSOAS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Idade INT NOT NULL,
    Sexo CHAR(1) NOT NULL,
    Cpf VARCHAR(14) UNIQUE NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Estado CHAR(2) NOT NULL,
    Profissao VARCHAR(100)
);
